### ISSUE TITLE
Composer field may be going away

### ISSUE THREAD

**Issue by cjcodeproj** [cjcodeproj/musicscan#16]
According to some TinyTag issue reports, the `composer` attribute will probably be going away, but the data will be available under the `extras` dictionary.

We should accommodate for this in the code.

Right now the `Track` object is almost an exact one to one field ratio for a TinyTag object, but the design goal of the class is to have a simple interface that gives direct access to the fields we want.

As a future consideration, `Track` needs to be engineered to handle input from other sources as well.

**Comment by mathiascode** [comment]
I decided to revert this change in tinytag, since the composer field is commonly used for classical music, and not worth breaking for existing users.

**Comment by cjcodeproj** [comment]
> I decided to revert this change in tinytag, since the composer field is commonly used for classical music, and not worth breaking for existing users.

This is good to know.  Thank you for the update.

**Comment by cjcodeproj** [comment]
# Closing Notes

Not an issue.
